import './globals.css'
import {Raleway} from "next/font/google"

export const metadata = {
  title: 'Indumentary Project',
  description: 'Generated by create next app',
}

const raleway = Raleway({
  weight: ["300", "400", "500", "700"],
  styles: ["italic", "normal"],
  subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {children}
      </body>
    </html>
  )
}
